import { GalaxyBackground, Header } from "@/components";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NPC__Tùng Portfolio",
  description: "Generated by create next app",
  verification: { google: "nw0HITN_N4EREo5YbgJMV7f-7Z_FAoEkPRo7-6BzNW4" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GalaxyBackground />
        <Header />
        {children}
        <Toaster position="bottom-right" expand richColors />
      </body>
    </html>
  );
}
